version: '3'

networks:
  laravel:


services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: "${PROJECT_NAME}_app"
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
      - node
    networks:
      - laravel

  mysql:
    image: mariadb:10.6
    container_name: "${PROJECT_NAME}_mariadb"
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    volumes:
      - mariadb_data:/var/lib/mysql

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: "${PROJECT_NAME}_php"
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:7.4.2-alpine
    container_name: "${PROJECT_NAME}_redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./www:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  node:
#    build:
#      context: ./dockerfiles
#      dockerfile: node.dockerfile
    image: node:18-alpine
    container_name: "${PROJECT_NAME}_npm"
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - laravel

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: "${PROJECT_NAME}_artisan"
    volumes:
      - ./www:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: mysql
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8085:80"
    depends_on:
      - mysql
    networks:
      - laravel

volumes:
  mariadb_data:
    driver: local